[project]
name = "pythonproject2"
version = "0.1.0"
description = "A project for analyzing transactions from an Excel file."
authors = [
    {name = "fedor shaporov",email = "shaporovfed@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest-cov (>=7.0.0,<8.0.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "pandas (>=2.3.3,<3.0.0)",
    "requests (>=2.32.5,<3.0.0)",
    "pytest-mock (>=3.15.1,<4.0.0)",
    "mock (>=5.2.0,<6.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.isort]
line_length = 119
multi_line_output = 3
include_trailing_comma = true
known_third_party = ["requests", "pandas"]
default_section = "THIRD_PARTY"
force_sort_within_sections = true

[tool.black]
line-length = 119
exclude = ".git"




[tool.mypy]
disallow_untyped_defs = true
warn_return_any = true


[dependency-groups]
lint = [
    "flake8 (>=7.3.0,<8.0.0)",
    "black (>=25.9.0,<26.0.0)",
    "mypy (>=1.18.2,<2.0.0)",
    "isort (>=7.0.0,<8.0.0)"
]
